# Generated by Django 3.0.8 on 2020-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=100)),
                ('surveillance_type', models.CharField(choices=[('FACE_MASK_DETECTION', 'Face Mask Detection'), ('CROWD_COUNTING', 'Crowd Counting'), ('SOCIAL_DISTANCING', 'Social Distancing Monitoring'), ('SPEED_MONITORING', 'Speed Monitoring')], max_length=32)),
            ],
        ),
    ]
