# Generated by Django 3.0.8 on 2020-08-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_surveillancecamera'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldata',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
