# Generated by Django 3.0.8 on 2020-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_criminaldata_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancecamera',
            name='is_blacklist_cam',
            field=models.BooleanField(default=False),
        ),
    ]
