# Generated by Django 3.0.8 on 2020-08-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_surveillancecamera_is_blacklist_cam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancecamera',
            name='surveillance_type',
            field=models.CharField(choices=[('FACE_MASK_DETECTION', 'Face Mask Detection'), ('CROWD_COUNTING', 'Crowd Counting'), ('SOCIAL_DISTANCING', 'Social Distancing Monitoring'), ('SPEED_MONITORING', 'Speed Monitoring'), ('BLACKLIST', 'Blacklisted Face Detection')], max_length=32),
        ),
    ]
